### ISSUE TITLE
Carlos' Concerns

### ISSUE THREAD

**Issue by Patrickmnts** [planetargon/ruby#1]
**#1** I feel like this is weird:

``` Ruby
# good
def self.create_translation(phrase_id,
                            phrase_key,
                            target_locale,
                            value,
                            user_id,
                            do_xss_check,
                            allow_verification)
  ...
end

# bad
def self.create_translation(phrase_id, phrase_key, target_locale,
                            value, user_id, do_xss_check, allow_verification)
  ...
end
```

It my opinion one shouldn’t be passing in that many arguments to a method call.
# 

**#2** The following seems unreadable to me. Thoughts? 

``` Ruby
<% if @presenter.guest_visa_russia? %>
  <%= icon_tile_for(I18n.t("email.reservation_confirmed_guest.visa.details_header",
                           :default => "Visa for foreign Travelers"),
                    :beveled_big_icon => "stamp") do %>
    <%= I18n.t("email.reservation_confirmed_guest.visa.russia.details_copy",
               :default => "Foreign guests travelling to Russia may need to obtain a visa...") %>
  <% end %>
<% end %>
```
# 

**#3** Are comments in methods like this valuable? The method name seems fairly descriptive

``` Ruby
# Applies transforms to American English that are common to
  # variants of all other English colonies.
  class AmericanToColonial
    ...
  end

  # Converts American to British English.
  # In addition to general Colonial English variations, changes "apartment"
  # to "flat".
  class AmericanToBritish < AmericanToColonial
    ...
  end
```

**#4** Don’t use variables called ret:

``` Ruby
  ret = @fallbacks[the_locale].dup
```
# 

**#5** I’m not liking the explicit return here:

``` Ruby
# bad
  render :text => 'Howdy' and return

  # good
  render :text => 'Howdy'
  return

  # still bad
  render :text => 'Howdy' and return if foo.present?

  # good
  if foo.present?
    render :text => 'Howdy'
    return
  end
```

**Comment by Patrickmnts** [comment]
@eddorre  I feel the majority of the points here (#1 - #3) are concerned with proper use of new lines and spacing/indentation, not actually whether or not the number of arguments are correct/desired.  

I feel like the longer list used for these examples gives a better idea of what can happen if the args for a method become rather lengthy, rather than using an example with < 3.  I think it's main use is in providing a good comparison about what #good should look like vs. #bad.  I believe they serve a realistic reference to projects that we have inherited, and are worth noting in our style guide, even if below #1 we say _TRY NOT TO USE 30 ARGS!_.

#5 - I agree with you here.  I would like to see this as: 

```
if foo.present?
  render : text => 'Howdy'
end
```

**Comment by hynkle** [comment]
I think the intention on # 5 is for avoiding AbstractController::DoubleRenderError, like if you had:

``` ruby
def show
  @resource = Resource.find(params[:id])
  render text: "I'm sorry, Dave; I can't let you do that", status: :unauthorized unless current_user.can?(:show, @resource)
  render 'show'
end
```

If the user isn't authorized, it tries to render the text as well as the 'show' template, which ends up causing the DoubleRenderError;

You can get away with not using a return by doing something like this:

``` ruby
def show
  @resource = Resource.find(params[:id])
  if current_user.can?(:show, @resource)
    render 'show'
  else
    render text: "I'm sorry, Dave; I can't let you do that", status: :unauthorized 
  end
end
```

But personally I like Python's precept that "flat is better than nested", so I like to return early (as the style guide suggests) and save an `else`:

``` ruby
def show
  @resource = Resource.find(params[:id])
  unless current_user.can?(:show, @resource)
    render text: "I'm sorry, Dave; I can't let you do that", status: :unauthorized
    return
  end
  render 'show'
end
```

What I like about this approach instead of `if`/`else` is that the "normal" state of affairs at the base indentation level of the method, which makes it quicker at scanning for what the happy path through this action is.

**Comment by davidsoncasey** [comment]
As far as #2, I've always liked starting arguments on the following line, and using levels of indentation for nested functions:

``` ERB
<% if @presenter.guest_visa_russia? %>
  <%= icon_tile_for(
    I18n.t(
      "email.reservation_confirmed_guest.visa.details_header",
      :default => "Visa for foreign Travelers"
    ),
    :beveled_big_icon => "stamp"
  ) do %>
    <%= I18n.t(
      "email.reservation_confirmed_guest.visa.russia.details_copy",
      :default => "Foreign guests travelling to Russia may need to obtain a visa..."
    ) %>
  <% end %>
<% end %>
```

This may be the Python programmer in me, but in my mind the indentation breaks the logic up visually in a way that you can very quickly tell how arguments correspond with functions in a nested case like this.

Or if you want to stay closer to the original, I think that moving the closing tag of the `icon_tile_for` statment helps a bit:

``` ERB
<% if @presenter.guest_visa_russia? %>
  <%= icon_tile_for(I18n.t("email.reservation_confirmed_guest.visa.details_header",
                           :default => "Visa for foreign Travelers"),
                    :beveled_big_icon => "stamp") 
  do %>
    <%= I18n.t("email.reservation_confirmed_guest.visa.russia.details_copy",
               :default => "Foreign guests travelling to Russia may need to obtain a visa...") %>
  <% end %>
<% end %>
```

**Comment by hynkle** [comment]
I'm with @davidsoncasey on his indentation preference for formatting calls to functions whose arguments are on multiple lines.

**Comment by hynkle** [comment]
Ugh how do I Github.  Sorry for the gratuitous close/open.

**Comment by davidsoncasey** [comment]
@hynkle @Patrickmnts @eddorre Do any of you have any other thoughts or suggestions here? I was thinking I'd close this out, and if there's more discussion about a specific spot we can open a new issue and/or create a pull request.

**Comment by davidsoncasey** [comment]
Closing this out.
