### ISSUE TITLE
Formatting of multi-line boolean expressions

### ISSUE THREAD

**Issue by hynkle** [planetargon/ruby#2]
The current guide says:

Indent succeeding lines in multi-line boolean expressions.

``` ruby
# good
def is_eligible?(user)
  Trebuchet.current.launch?(ProgramEligibilityHelper::PROGRAM_TREBUCHET_FLAG) &&
    is_in_program?(user) &&
    program_not_expired
end

# bad
def is_eligible?(user)
  Trebuchet.current.launch?(ProgramEligibilityHelper::PROGRAM_TREBUCHET_FLAG) &&
  is_in_program?(user) &&
  program_not_expired
end
```

I find both of these difficult to interpret at first scan, as my eyes have to follow the ragged right edge of the lines instead of the even left edge.  For this reason, I prefer having the `&&` at the beginning of the line, as then the structure of what is going on is easier to understand at a glance.  In semicolon-requiring languages, no problem, but in Ruby doing that necessitates putting a backslash at the end of the previous line (to make the parser realize that the end of the line isn't the end of the statement).  I still like it better, but I don't know that I've ever seen it as a style elsewhere.  Thoughts on this?:

``` ruby
def is_eligible?(user)
  Trebuchet.current.launch?(ProgramEligibilityHelper::PROGRAM_TREBUCHET_FLAG) \
  && is_in_program?(user) \
  && program_not_expired
end
```

**Comment by planetargon** [comment]
@hynkle I agree with you - putting the `&&` at the beginning of the line makes it clear that it's a continuation of the boolean statement on the line before. In a case like this, I also like defining an intermediate variable, so that the boolean statement itself is easier to look at and interpret.
```Ruby
def is_eligible?(user)
  launch = Trebuchet.current.launch?(ProgramEligibilityHelper::PROGRAM_TREBUCHET_FLAG)
  launch && is_in_program?(user) && program_not_expired
end
```

**Comment by davidsoncasey** [comment]
@hynkle I agree with you - putting the `&&` at the beginning of the line makes it clear that it's a continuation of the boolean statement on the line before. In a case like this, I also like defining an intermediate variable, so that the boolean statement itself is easier to look at and interpret.

``` Ruby
def is_eligible?(user)
  launch = Trebuchet.current.launch?(ProgramEligibilityHelper::PROGRAM_TREBUCHET_FLAG)
  launch && is_in_program?(user) && program_not_expired
end
```

Granted, that fist line may be over 100 characters, so you could do something like:

``` Ruby
def is_eligible?(user)
  trebuchet_flag = ProgramEligibilityHelper::PROGRAM_TREBUCHET_FLAG
  launch = Trebuchet.current.launch?(trebuchet_flag)
  launch && is_in_program?(user) && program_not_expired
end
```

Same number of lines, but I think it's a little easier to follow. Curious to see if others don't like the creation of extra variables.
